services:
  web: 
    image: nginx:latest
    container_name: sgs-nginx-web
    ports: 
      - "80:80"
    volumes:
      # - .:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app: 
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: sgs-php-application
    # volumes:
    #   - .:/var/www/html
    depends_on:
      - db

  db:
    build: 
      context: .
      dockerfile: ./sql/mysql/Dockerfile
    container_name: sgs-mysql-db
    command: [
      '--default-authentication-plugin=mysql_native_password', 
      '--character-set-server=utf8', 
      '--collation-server=utf8_general_ci'
    ]
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: